// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGIds
{
        public const string achievement_farm_is_mine = "CgkIjYG594ESEAIQDQ"; // <GPGSID>
        public const string achievement_paca_can_watch = "CgkIjYG594ESEAIQAQ"; // <GPGSID>
        public const string achievement_can_you_jump = "CgkIjYG594ESEAIQDg"; // <GPGSID>
        public const string achievement_oh_you_can_jump = "CgkIjYG594ESEAIQDw"; // <GPGSID>
        public const string achievement_beginner_billionaire = "CgkIjYG594ESEAIQGA"; // <GPGSID>
        public const string achievement_is_this_wolfs_farm = "CgkIjYG594ESEAIQBw"; // <GPGSID>
        public const string achievement_noob = "CgkIjYG594ESEAIQAg"; // <GPGSID>
        public const string achievement_my_own_paca = "CgkIjYG594ESEAIQCA"; // <GPGSID>
        public const string achievement_novice_billionaire = "CgkIjYG594ESEAIQFw"; // <GPGSID>
        public const string achievement_farm_sweet_farm = "CgkIjYG594ESEAIQDA"; // <GPGSID>
        public const string achievement_jumper_novice = "CgkIjYG594ESEAIQEg"; // <GPGSID>
        public const string achievement_greeeedy = "CgkIjYG594ESEAIQHQ"; // <GPGSID>
        public const string achievement_jumper_beginner = "CgkIjYG594ESEAIQEw"; // <GPGSID>
        public const string achievement_never_skip_leg_day = "CgkIjYG594ESEAIQEQ"; // <GPGSID>
        public const string achievement_wolf_attack = "CgkIjYG594ESEAIQBA"; // <GPGSID>
        public const string achievement_expert_billionaire = "CgkIjYG594ESEAIQGQ"; // <GPGSID>
        public const string achievement_raaaaawr = "CgkIjYG594ESEAIQBQ"; // <GPGSID>
        public const string achievement_greeeeedy = "CgkIjYG594ESEAIQHg"; // <GPGSID>
        public const string achievement_jump_for_your_health = "CgkIjYG594ESEAIQEA"; // <GPGSID>
        public const string achievement_10_little_paca = "CgkIjYG594ESEAIQCQ"; // <GPGSID>
        public const string achievement_master_billionaire = "CgkIjYG594ESEAIQGg"; // <GPGSID>
        public const string achievement_wolf_dinner = "CgkIjYG594ESEAIQBg"; // <GPGSID>
        public const string achievement_greeedy = "CgkIjYG594ESEAIQHA"; // <GPGSID>
        public const string achievement_greedy = "CgkIjYG594ESEAIQGw"; // <GPGSID>
        public const string achievement_jumper_expert = "CgkIjYG594ESEAIQFA"; // <GPGSID>
        public const string achievement_paca_is_love_paca_is_life = "CgkIjYG594ESEAIQCg"; // <GPGSID>
        public const string achievement_my_pretty_farm = "CgkIjYG594ESEAIQCw"; // <GPGSID>
        public const string achievement_jump_1st_time = "CgkIjYG594ESEAIQAA"; // <GPGSID>
        public const string achievement_jumper_master = "CgkIjYG594ESEAIQFQ"; // <GPGSID>
        public const string achievement_practice_makes_perfect = "CgkIjYG594ESEAIQFg"; // <GPGSID>

}

